
// home模块-用户选择当前位置
const HOMECHOSEPOS = 'HOMECHOSEPOS'
// home模块-确认订单页缓存数据和状态
const ORDERCONFIRMTEMPDATA = 'ORDERCONFIRMTEMPDATA'

// ucenter模块-我的地址-用户选择地址
const ADDRESSCHOSEPOS = 'ADDRESSCHOSEPOS'
// ucenter模块-我的地址-用户地址表单缓存
const TEMPCHOSEPOS = 'TEMPCHOSEPOS'
// ucenter模块-我的地址列表
const USERADDRESSLIST = 'USERADDRESSLIST'

export {
  HOMECHOSEPOS,
  ORDERCONFIRMTEMPDATA,
  TEMPCHOSEPOS,
  ADDRESSCHOSEPOS,
  USERADDRESSLIST
}
